### ISSUE TITLE
Repair endpoint starts cluster tasks on nodes not running Cassandra

### ISSUE THREAD

**Issue by verma7** [mesosphere/dcos-cassandra-service#177]
We are running Aurora and Cassandra frameworks in the same Mesos cluster. 

I tried to start a repair by using:

```
curl -H 'Content-Type: application/json' \
     -X PUT -d '{ "nodes" : [ "*" ] }' \
     http://appdocker968-sjc1.prod.uber.internal:5287/v1/repair/start
```

It starts accepting offers from the non-Cassandra machines, launches the task and then fails. This leaves dynamically reserved resources on all of the Aurora machines on which it has attempted to launch (the role of the framework is `cassandra-cstar-token`:
Excerpt from the http://mesos-master:5050/state endpoint:

```
{
id: "ec1f56cf-a66c-48cd-880c-020b430b0d1a-S4",
pid: "slave(1)@10.28.20.29:5051",
hostname: "compute131-sjc1.prod.uber.internal",
registered_time: 1466724399.95873,
reregistered_time: 1466724400.11227,
resources: {
cpus: 24,
disk: 1665158,
mem: 120635,
ports: "[31000-32000]"
},
used_resources: {
cpus: 5.75,
disk: 6144,
mem: 12672,
ports: "[31439-31439, 31583-31583, 31755-31755, 31787-31787]"
},
offered_resources: {
cpus: 16.25,
disk: 1659014,
mem: 107451,
ports: "[31000-31438, 31440-31582, 31584-31754, 31756-31786, 31788-32000]"
},
reserved_resources: {
cassandra-cstar-token: {
cpus: 1,
disk: 0,
mem: 256
}
},
unreserved_resources: {
cpus: 22,
disk: 1665158,
mem: 120123,
ports: "[31000-32000]"
},
attributes: {
host: "compute131-sjc1",
kernel: 3.18,
pipeline: "us1",
pod: "c",
rack: 337
},
active: true,
version: "0.28.2-22"
}
```

Is this a bug caused due to passing `null` as the agentsToColocate here: https://github.com/mesosphere/dcos-cassandra-service/blob/master/cassandra-scheduler/src/main/java/com/mesosphere/dcos/cassandra/scheduler/offer/ClusterTaskOfferRequirementProvider.java#L108 ?

I think it should colocate the cluster repair task on the nodes running the Cassandra tasks.

**Comment by verma7** [comment]
@mohitsoni @kow3ns

**Comment by keithchambers** [comment]
Adding @gabrielhartmann

**Comment by gabrielhartmann** [comment]
Hi @verma7.  What version of the service are you running?  This defect has been resolved for the last couple releases.  You are correct that the null, passed in the location you indicate used to contributed to the issue.  If you look at the CassandraContainer class now and the template it creates, you will see that all Cluster Tasks are now generated off of this template and are therefore appropriately bound to Cassandra nodes and indeed use pre-reserved resources within the same Executor as each Cassandra node to guarantee that they can always be successfully launched and not starved for resources.  If you have any questions, please let me know.

**Comment by verma7** [comment]
Thanks for your reply @gabrielhartmann .

We are running a version that was forked on May 13 (https://github.com/verma7/dcos-cassandra-service/compare/statsd-metrics). Can you point me to the specific commits that fixed this issue? How has it been fixed if we still return `null` here?

We are already running 5 production Cassandra clusters. So it will be good to know if there have been any changes to the zookeeper format or any backwards incompatible changes and how to migrate the existing clusters to it.

Is there a release process that you guys follow for dcos-cassandra-service? What commit/tag would be a good point to rebase our internal changes on?

**Comment by triclambert** [comment]
Hi @verma7.  Instead of backporting that change, perhaps we should talk about how we can get you caught up.  What do you think?

**Comment by nickbp** [comment]
Closing as they've been able to catch up.
