### ISSUE TITLE
zookeeper dependency binaries are missing

### ISSUE THREAD

**Issue by vargup** [mesosphere/dcos-cassandra-service#199]
I pulled latest version today, and unable to run clean build. 19 tests are failing due to zookeeper binaries are missing.

Stacktrace can be found here:

http://stackoverflow.com/questions/38705618/dcos-cassandra-mesos-project-build-failing-for-quorumpeermain-class-not-found

**Comment by kow3ns** [comment]
This is not an artifact of the project configuration. This is not reproducible on our build servers for any branch, and, after investigation by multiple engineers, we are not able to reproduce this.
