### ISSUE TITLE
Creating persistent volume does not work with Mesos 1.0

### ISSUE THREAD

**Issue by verma7** [mesosphere/dcos-cassandra-service#215]
Mesos 1.0 now enforces that DiskInfo principal is equal to framework/operator principal (https://issues.apache.org/jira/browse/MESOS-5005) or else the creation of persistent volume fails. So we need to set this during the create operation.

**Comment by kow3ns** [comment]
It looks like this issue is resolved in master. The disk-info principal is currently set.

**Comment by mohitsoni** [comment]
@verma7 Is this resolved for you now ? If yes, can you please close this.

**Comment by verma7** [comment]
@kow3ns  @mohitsoni Are you sure this issue has been resolved? 

I still see that the principal is not set here: 
1. https://github.com/mesosphere/dcos-cassandra-service/blob/master/cassandra-commons/src/main/java/com/mesosphere/dcos/cassandra/common/util/TaskUtils.java#L111, or
2. https://github.com/mesosphere/dcos-commons/blob/master/src/main/java/org/apache/mesos/offer/OfferEvaluator.java#L325, 

but is being set here: 
3. https://github.com/mesosphere/dcos-commons/blob/master/src/main/java/org/apache/mesos/offer/ResourceUtils.java#L424

Are 1 and 2 not being used? Is so we should remove them or set the principal there too.

**Comment by verma7** [comment]
Reply from @kow3ns through Slack:

analysis of the call trace for the function mentioned in the issue leads me to believe it is dead code
dcos-commons does the Volume creation and it sets the principal as per the Mesos requirement

**Comment by verma7** [comment]
Closing the issue as we are not affected by it anymore.
