### ISSUE TITLE
Repair job gets assigned to a node other than the one needs to be repaired

### ISSUE THREAD

**Issue by szhou1234** [mesosphere/dcos-cassandra-service#229]
The consequence is that the executor is unable to connect to the Cassandra daemon process because it uses 127.0.0.1. Looks like there are two bugs in the scheduler:
1. Repair job should use NodePlacementStrategy
2. NodePlacementStrategy doesn't return the expected nodes to avoid.

I'm going to submit a pull request to fix this but let me know if I misunderstand.

**Comment by dylanwilder** [comment]
Correct me if I'm wrong but this looks like a bug in ClusterTaskPlacementStrategy (I'm on master). Code reads 

```java
@Override
    public List<Protos.SlaveID> getAgentsToColocate(Protos.TaskInfo taskInfo) {
        List<Protos.SlaveID> agentsToColocate = new ArrayList<>();
        // Collocate this task with the corresponding Cassandra node task
        Arrays.asList(taskInfo.getSlaveId());
        LOGGER.info("Collocating task: {} with agent: {}",
                taskInfo.getTaskId().getValue(), agentsToColocate);
        return agentsToColocate;
    }
```

but should be 

```java
@Override
    public List<Protos.SlaveID> getAgentsToColocate(Protos.TaskInfo taskInfo) {
        List<Protos.SlaveID> agentsToColocate = new ArrayList<>();
        // Collocate this task with the corresponding Cassandra node task
        agentsToColocate.add(taskInfo.getSlaveId());
        LOGGER.info("Collocating task: {} with agent: {}",
                taskInfo.getTaskId().getValue(), agentsToColocate);
        return agentsToColocate;
    }
```

**Comment by nickbp** [comment]
That code snipped indeed looks like it'd have been the issue. The placement logic has been replaced by a common upstream version provided by [dcos-commons](https://github.com/mesosphere/dcos-commons). Marking this as closed.
