### ISSUE TITLE
Unable to deploy cassandra on dc/os 1.8.2

### ISSUE THREAD

**Issue by emanuelemaffeo** [mesosphere/dcos-cassandra-service#232]
Same error is also given during dse deploy.

Exception in logs is:

> Error injecting constructor, org.apache.mesos.config.ConfigStoreException: Failed to retrieve current target configuration from path '/dcos-service-datastax/ConfigTarget'
>   at com.mesosphere.dcos.cassandra.scheduler.seeds.SeedsManager.<init>(SeedsManager.java:105)
>   at com.mesosphere.dcos.cassandra.scheduler.SchedulerModule.configure(SchedulerModule.java:204)
>   while locating com.mesosphere.dcos.cassandra.scheduler.seeds.SeedsManager
> 1 error
>     at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
>     at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
>     at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
>     at com.google.inject.Guice.createInjector(Guice.java:96)
>     at com.google.inject.Guice.createInjector(Guice.java:73)
>     at com.google.inject.Guice.createInjector(Guice.java:62)
>     at com.mesosphere.dcos.cassandra.scheduler.Main.run(Main.java:67)
>     at com.mesosphere.dcos.cassandra.scheduler.Main.run(Main.java:23)
>     at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:40)
>     at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:77)
>     at io.dropwizard.cli.Cli.run(Cli.java:70)
>     at io.dropwizard.Application.run(Application.java:80)
>     at com.mesosphere.dcos.cassandra.scheduler.Main.main(Main.java:28)
> Caused by: org.apache.mesos.config.ConfigStoreException: Failed to retrieve current target configuration from path '/dcos-service-datastax/ConfigTarget'
>     at org.apache.mesos.curator.CuratorConfigStore.getTargetConfig(CuratorConfigStore.java:180)
>     at com.mesosphere.dcos.cassandra.scheduler.config.DefaultConfigurationManager.getTargetName(DefaultConfigurationManager.java:204)
>     at com.mesosphere.dcos.cassandra.scheduler.config.DefaultConfigurationManager.getTargetConfig(DefaultConfigurationManager.java:213)
>     at com.mesosphere.dcos.cassandra.scheduler.seeds.SeedsManager.<init>(SeedsManager.java:139)
>     at com.mesosphere.dcos.cassandra.scheduler.seeds.SeedsManager$$FastClassByGuice$$91cd171b.newInstance(<generated>)
>     at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
>     at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
>     at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
>     at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
>     at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
>     at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
>     at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
>     at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
>     at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
>     at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
>     at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
>     at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
>     at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
>     at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
>     at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
>     ... 11 more

**Comment by mohitsoni** [comment]
@emanuelemaffeo Did you try the [latest version](https://github.com/mesosphere/dcos-cassandra-service/releases) ?

**Comment by emanuelemaffeo** [comment]
Yes, now everything works fine.

Thank you!
