### ISSUE TITLE
Monitoring with nodetool

### ISSUE THREAD

**Issue by pdehlke** [mesosphere/dcos-cassandra-service#237]
My cassandra deployments- and I suspect a lot of other people's- is heavily monitored by examination of the output of regularly run nodetool tasks (compactionstats, gossipinfo, tpstats, status, etc) and other JMX based tooling.  It's unclear how to reproduce that stuff in this framework, given that JMX is not exposed outside the node containers. 

Advice on this? Am I missing something? Anyone working on an approach?

**Comment by mohitsoni** [comment]
@pdehlke We are working on open-sourcing our metrics feature (which is currently enterprise only), which uses statsd for exposing all our metrics. Stay tuned.

**Comment by pdehlke** [comment]
Excellent. Looking forward to that!

**Comment by pomber** [comment]
So, is it now possible to use nodetool with this service?  
Couldn't find any documentation.

**Comment by triclambert** [comment]
@pomber this repo is deprecated.  PTAL mesosphere/dcos-commons/frameworks/cassandra.  (Created a PR to update the readme:  https://github.com/mesosphere/dcos-cassandra-service/pull/463.)
