### ISSUE TITLE
Unable to Install Package Cassandra

### ISSUE THREAD

**Issue by sreeraaman** [mesosphere/dcos-cassandra-service#268]
While trying to install cassandra in DC/OS 1.8 in EC2, we get the following error.

fetch 'https://downloads.mesosphere.com/cassandra/assets/apache-cassandra-3.0.8-bin-dcos.tar.gz': Error downloading resource, received HTTP return code 403

We tried installed dse  5 package which got installed. Got the cli package as well installed. However, while trying to query the cassandra connections via 
dcos cassandra connection it throws the following exception:

/service/cassandra/v1/nodes/list failed: 500 Internal Server Error
2016/09/29 19:07:08 - Did you provide the correct service name? Currently using 'cassandra', specify a different name with '--name=<name>'.
2016/09/29 19:07:08 - Was the service recently installed? It may still be initializing, Wait a bit and try again.

**Comment by nickbp** [comment]
Hello, this should be fixed now, have you tried again recently? Around that time we were still deploying the new artifacts to our downloads mirror so there was a window where new installations would have failed. Feel free to reopen this issue if you're still seeing the problem.
