### ISSUE TITLE
Unable to Setup Cassandra Cluster

### ISSUE THREAD

**Issue by NastyNash** [mesosphere/dcos-cassandra-service#269]
Followed the Documentation and Installation steps mentioned:
After installation of package when i check cassandra connection this is what i get :

dcos cassandra connection
{"address":[],"dns":[]}

stdout on my marathon :
**INFO  [2016-09-29 21:53:53,562] org.eclipse.jetty.setuid.SetUIDListener: Opened DC/OS Cassandra Service@1da4b6b3{HTTP/1.1}{0.0.0.0:9000}
INFO  [2016-09-29 21:53:53,565] org.eclipse.jetty.server.Server: jetty-9.2.14.v20151106
INFO  [2016-09-29 21:53:54,372] org.apache.mesos.scheduler.SchedulerDriverFactory: Creating unauthenticated MesosSchedulerDriver for scheduler[com.mesosphere.dcos.cassandra.scheduler.CassandraScheduler@4393593c],** frameworkInfo[user: "root"
name: "cassandra"
id {
  value: "dae7eb1e-00d3-4417-ad5a-9a1135abc00a-0001"
}
failover_timeout: 604800.0
checkpoint: true
role: "cassandra-role"
principal: "cassandra-principal"
], masterUrl[zk://master.mesos:2181/mesos]
INFO  [2016-09-29 21:53:56,368] com.mesosphere.dcos.cassandra.scheduler.CassandraScheduler: Starting driver...
INFO  [2016-09-29 21:53:56,369] com.mesosphere.dcos.cassandra.scheduler.CassandraScheduler: Driver started with status: DRIVER_RUNNING
ERROR [2016-09-29 21:53:56,662] com.mesosphere.dcos.cassandra.scheduler.CassandraScheduler: Scheduler driver error: Framework has been removed
INFO  [2016-09-29 21:54:07,365] io.dropwizard.jersey.DropwizardResourceConfig: The following paths were found for the configured resources:
5:15 PM
{"name":"cassandra","id":"","version":"1.0.0","user":"root","cluster":"cassandra-cluster","role":"cassandra-role","principal":"cassandra-principal","failover_timeout_s":604800,"secret":"","checkpoint":true}
5:16 PM
{"address":[],"dns":[]} connection
5:17 PM
plan {"phases":[],"errors":[],"status":"COMPLETE"}

**Comment by nickbp** [comment]
Hello, the 'framework has been removed' error typically is the result of installing the service, uninstalling it, and then reinstalling it, without running the framework cleaner (`janitor.py`) after the uninstall.

We're still working on a better cleanup solution following uninstall, but at the moment you can perform the instructions laid out here: https://docs.mesosphere.com/1.8/usage/service-guides/cassandra/uninstall/ (see the purple 'framework cleaner' link -- it can be a little hard to see)

```
your-machine$ dcos node ssh --master-proxy --leader
cluster-leader$ docker run mesosphere/janitor /janitor.py -r cassandra-role -p cassandra-principal -z dcos-service-cassandra [--auth_token=your-auth-token-if-DCOS-enterprise]
```

If you're curious, here's what's going on:
- The Cassandra Scheduler registers the service with Mesos and stores the resulting framework id to ZK (this allows the scheduler to automatically reconnect to Mesos in the event of the scheduler task being restarted)
- The service is uninstalled via eg 'dcos package uninstall cassandra': The framework is unregistered from Mesos and Mesos adds it to a list of invalid framework ids.
- The service is reinstalled without first deleting the ZK data mentioned above.
- The Cassandra Scheduler sees the old framework id in ZK and attempts to register against it with Mesos.
- Mesos sees that the framework id is in its list of invalid framework ids and returns the 'framework has been removed' error you see there.

Feel free to reopen this issue if you're still seeing problems.

**Comment by NastyNash** [comment]
Thankyou for your reply.
Encountered a new issue.

colluni@TUSTX002MLVT06l:/nischal/cass-dcos$ ./dcos package list
NAME       VERSION       APP         COMMAND    DESCRIPTION
cassandra  1.0.16-3.0.8  /cassandra  cassandra  Apache Cassandra running on DC/OS

colluni@TUSTX002MLVT06l:/nischal/cass-dcos$ ./dcos cassandra connection
2016/09/30 15:35:48 Unable to retrieve configuration value core.dcos_url (DC/OS Cluster URL) from CLI. Run 'dcos config set core.dcos_url http://your-cluster.com' to configure.:
Error: exec: "dcos": executable file not found in $PATH
Output:
CLI configuration value core.dcos_url (DC/OS Cluster URL) is missing/unset. Run 'dcos config set core.dcos_url http://your-cluster.com' to configure.

But my core.dcos_url is already set as shown below:
colluni@TUSTX002MLVT06l:/nischal/cass-dcos$ ./dcos config set core.dcos_url http://192.168.65.90
[core.dcos_url]: set to 'http://192.168.65.90'

**Comment by NastyNash** [comment]
I could fix the avoid issue.

Whereas when i am trying to come up with the cluster there is only one instance of cassandra coming up. Maybe its related to the resources. 
Below are the **Stderr logs**
I1003 08:15:19.772804 30786 group.cpp:349] Group process (group(1)@192.168.65.111:45332) connected to ZooKeeper
I1003 08:15:19.773187 30786 group.cpp:831] Syncing group operations: queue size (joins, cancels, datas) = (0, 0, 0)
I1003 08:15:19.773239 30786 group.cpp:427] Trying to create path '/mesos' in ZooKeeper
I1003 08:15:19.850381 30786 detector.cpp:152] Detected a new leader: (id='7')
I1003 08:15:19.851227 30786 group.cpp:700] Trying to get '/mesos/json.info_0000000007' in ZooKeeper
I1003 08:15:19.855691 30787 detector.cpp:479] A new leading master (UPID=master@192.168.65.90:5050) is detected
I1003 08:15:19.855770 30787 sched.cpp:326] New master detected at master@192.168.65.90:5050
I1003 08:15:19.856003 30787 sched.cpp:336] No credentials provided. Attempting to register without authentication
I1003 08:15:19.948170 30787 sched.cpp:1127] Got error 'Framework has been removed'
I1003 08:15:19.948197 30787 sched.cpp:1937] Asked to abort the driver
I1003 08:15:19.948563 30787 sched.cpp:1173] Aborting framework 'ea576c73-6cf4-485f-9bf1-0f9cd82a15f6-0001'
2016-10-03 08:16:33,307:30720(0x7ff192ffd700):ZOO_WARN@zookeeper_interest@1557: Exceeded deadline by 13ms

**.

**Comment by nickbp** [comment]
That error is a bit confusing and should be cleaned up. Filed https://github.com/mesosphere/dcos-commons/issues/176 to solve that

I think what's really happening is a result of the 'dcos cassandra' command running from a different binary which calls into the main 'dcos' binary. It does this via the typical executable lookup against entries in your `$PATH`. You should be able to fix the problem via one of the following:

- Move the `dcos` binary into somewhere like `/usr/local/bin` (this would also allow running `dcos` commands without needing the ./)
- Update your shell's `PATH` permanently via eg `.bashrc` or `.profile`. (same outcome as above)
- Run `dcos cassandra` commands with a temporary PATH pointing to the location of the `dcos` binary. For example (with the example of `dcos` in `.`): `PATH=$PATH:. dcos cassandra -h`

**Comment by nickbp** [comment]
That 'framework has been removed' error looks similar to the issue before. Have you been able to run the `dcos node ssh` + `docker run mesosphere/janitor` commands described before? It sounds like they need to be run again

**Comment by NastyNash** [comment]
yes i was able to run the mesosphere/janitor commands. 
But nothing really changed. i reinstalled the cassandra package and ended up getting just one instance running on marathon then followed my stderr logs.
Dont know if this helps , this is the command i used and then entered "**yes**"

**./dcos package install cassandra
DC/OS Cassandra Service default configuration requires 3 nodes each with 1.5 CPU shares, 5376MB of memory and 11264MB of disk for running Cassandra Nodes. And, 1 node with 0.5 CPU shares, 2048MB of memory for running the service scheduler.
Continue installing? [yes/no] yes
Installing Marathon app for package [cassandra] version [1.0.16-3.0.8]
Installing CLI subcommand for package [cassandra] version [1.0.16-3.0.8]
New command available: dcos cassandra
DC/OS Apache Cassandra has been successfully installed!

	Documentation: https://docs.mesosphere.com/usage/services/cassandra/
	Issues: https://dcosjira.atlassian.net/projects/CASSANDRA/issues**

**Comment by nickbp** [comment]
Maybe try looking at the Exhibitor interface on the master node, to view the state of ZK:

1. Open http://url-for-your-master-node/exhibitor 
1. Explorer tab, expand '/' folder
1. Check for an entry named 'dcos-service-cassandra'. If 'dcos-service-cassandra' exists then the janitor failed to complete. 
1. To manually delete 'dcos-service-cassandra' (note: this cannot be undone):
  1. Select 'dcos-service-cassandra' from the list
  1. Click 'modify' at the bottom of the page:
    1. Type = Delete
    1. Username / Ticket / Reason = any text you want (eg 'abc'), but they still need to be filled in
  1. Click Next, then OK.

**Comment by NastyNash** [comment]
colluni@TUSTX002MLVT06l:/nischal/cass-dcos$ ./dcos package install cassandra
DC/OS Cassandra Service default configuration requires 3 nodes each with 1.5 CPU shares, **5376MB of memory and 11264MB of disk for running Cassandra Nodes**. And, 1 node with 0.5 CPU shares, 2048MB of memory for running the service scheduler.
Continue installing? [yes/no]

**Comment by NastyNash** [comment]
Regarding the resources, how do i modify the disk space allocation. I tried using a sample json file and passing it as an option while installing the package but still it take up the default configurations.

colluni@TUSTX002MLVT06l:/nischal/cass-dcos$ ./dcos package install cassandra
DC/OS Cassandra Service default configuration requires 3 nodes each with 1.5 CPU shares, **5376MB of memory and 11264MB of disk for running Cassandra Nodes**. And, 1 node with 0.5 CPU shares, 2048MB of memory for running the service scheduler.
Continue installing? [yes/no]

**Comment by NastyNash** [comment]
I have executed all of your above mentioned steps. Made a fresh installation of cassandra package.
During installation i am asked : 
**DC/OS Cassandra Service default configuration requires 3 nodes each with 1.5 CPU shares, 5376MB of memory and 11264MB of disk for running Cassandra Nodes. And, 1 node with 0.5 CPU shares, 2048MB of memory for running the service scheduler.
Continue installing? [yes/no]**

After the completion of installation i come back to the original issue of **'framework has been removed'** error. I suppose there is a problem with resources and could you please help me fixing it.

**Comment by nickbp** [comment]
Yes that's the recommended default configuration, if you don't have that many nodes/resources available you can reduce the requirements.

See for example: https://github.com/mesosphere/dcos-cassandra-service#minimal-installation

**Comment by NastyNash** [comment]
ok ..
Meanwhile i have come up with just one node and the container is up and healthy on marathon but i am unable to see it as a running container when i ssh to my agent where the container is running.
**docker ps** doesnt display any running containers. Whereas mesos shows it as running.
ps -ef tells me that cassandra is running as a service.. really confused as to how is everything happening.. How do i get inside the cassandra container and run cqlsh to create keyspaces, etc.

Thanks

**Comment by NastyNash** [comment]
Hello,
How do i increase my resources on mesos. Unable to launch more nodes because of limited resource.

Thanks

**Comment by mohitsoni** [comment]
@NastyNash If you are unable to launch more nodes because of lack of free resources, I would suggest you add more capacity to the Mesos cluster, by adding more Mesos Agents. 
Are you using DC/OS ? If yes, then I would suggest you to please head over to [DC/OS Community Slack](http://chat.mesosphere.com/?_ga=1.131344335.1123808857.1460928806), as that would be the right place to get more guidance on this.
