### ISSUE TITLE
Specify role for scheduler and tasks

### ISSUE THREAD

**Issue by gdhgdhgdh** [mesosphere/dcos-cassandra-service#280]
In https://github.com/mesosphere/dcos-cassandra-service/blob/master/README.md#service-configuration

```
{
    "service": {
        "name": "cassandra2",
        "cluster" : "dcos_cluster",
        "role": "cassandra_role",
        "data_center" : "dc2",
...
```

How do I use `role` ? It isn't mentioned in the https://github.com/mesosphere/universe/blob/version-3.x/repo/packages/C/cassandra/16/config.json at all :(

**Comment by mohitsoni** [comment]
@gdhgdhgdh The role is implicitly configured as: `<service.name>-role`. In your example, it will be `cassandra2-role`.

**Comment by nickbp** [comment]
Closing this ticket, feel free to reopen if there are further issues
