### ISSUE TITLE
Cluster Repair task 

### ISSUE THREAD

**Issue by dylanwilder** [mesosphere/dcos-cassandra-service#302]
[Reference](https://github.com/mesosphere/dcos-cassandra-service/blob/master/cassandra-scheduler/src/main/java/com/mesosphere/dcos/cassandra/scheduler/resources/RepairRequest.java#L63) Repair request seems to require the nodes field to be specified.  This prevents one from automatically repairing the entire cluster

**Comment by verma7** [comment]
@dylanwilder You can specify the nodes as `*` which will repair all the nodes.

**Comment by dylanwilder** [comment]
thanks @verma7. I realized that from the code shortly after posting.  Does it make sense (from a interface consistency perspective) to support both?

**Comment by nickbp** [comment]
Looks like both an explicit list and '*' are supported: https://github.com/mesosphere/dcos-cassandra-service/blob/master/cli/dcos-cassandra/main.go#L306
