### ISSUE TITLE
how to running dcos-cassandra-service on pure mesos cluster

### ISSUE THREAD

**Issue by chjhaijiang** [mesosphere/dcos-cassandra-service#331]
We only have mesos cluster without any principal.  I want to know how to depoly it on **pure** mesos cluster? Any one done that before?

**Comment by triclambert** [comment]
You can indeed do this, but you'll have to do a bunch of work yourself to figure out how to run the scheduler.  (This is why it's easier to use DC/OS to run Mesos!)  Check out the `universe/` directory in this repo for references to the necessary artifacts, Marathon config, environment variables, etc.

**Comment by chjhaijiang** [comment]
OK,  Thanks. I had deployed it on pure mesos cluster successfully.

**Comment by triclambert** [comment]
Great news!  

For more about DC/OS frameworks, check out [mesosphere/dcos-commons](https://github.com/mesosphere/dcos-commons) and our [FAQ](https://github.com/mesosphere/dcos-commons/blob/master/docs/faq.md).
