### ISSUE TITLE
Downscaling the Cassandra cluster

### ISSUE THREAD

**Issue by alukyan** [mesosphere/dcos-cassandra-service#416]
We have deployed DCOS Cassandra cluster with 19 nodes. Now we see that we do not have so much data and would like to downscale the cluster. But we are unable to do this via DCOS Cassandra CLI or Marathon app by reducing number of Cassandra nodes.

Can community recommend what to do in this case - it seem like pretty basic scenario - resizing cluster size.

**Comment by cscetbon** [comment]
Any comment on that ticket ? Is it not supported ?

**Comment by triclambert** [comment]
This operation is currently not supported.  See `docs/limitations.md`.
