### ISSUE TITLE
Cancel in-progress backup / restore 

### ISSUE THREAD

**Issue by keithchambers** [mesosphere/dcos-cassandra-service#74]
Backups / restores execute serially, which means they could take hours or days. It would be useful to allow operators to cancel an in-progress backup / restore.

**Comment by nickbp** [comment]
https://github.com/mesosphere/dcos-cassandra-service/blob/master/cli/dcos-cassandra/main.go#L221
https://github.com/mesosphere/dcos-cassandra-service/blob/master/cli/dcos-cassandra/main.go#L239
